import React, { useState, useEffect } from 'react';
import { Copy, Check, RotateCcw, Mail, AlertCircle } from 'lucide-react';

interface EmailSectionProps {
  autoGeneratedEmail: string;
}

export const EmailSection: React.FC<EmailSectionProps> = ({ autoGeneratedEmail }) => {
  const [emailText, setEmailText] = useState(autoGeneratedEmail);
  const [isCustomEdited, setIsCustomEdited] = useState(false);
  const [copied, setCopied] = useState(false);

  // Sync automatic changes if user has not manually customized the text
  useEffect(() => {
    if (!isCustomEdited) {
      setEmailText(autoGeneratedEmail);
    }
  }, [autoGeneratedEmail, isCustomEdited]);

  const handleTextChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEmailText(e.target.value);
    setIsCustomEdited(true);
  };

  const handleRestore = () => {
    setEmailText(autoGeneratedEmail);
    setIsCustomEdited(false);
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(emailText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Falha ao copiar texto:', err);
    }
  };

  return (
    <section className="bg-white rounded-xl border border-slate-200 p-5 sm:p-6 shadow-xs flex flex-col justify-between">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-slate-100 gap-3 mb-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400">
              5. Solicitação de Recarga (Email Diretoria)
            </h2>
            <span className="p-1 rounded-md bg-blue-50 text-blue-600">
              <Mail className="w-3.5 h-3.5" />
            </span>
          </div>
          <p className="text-xs text-slate-500 font-medium mt-0.5">
            Texto gerado dinamicamente com base nas previsões e campanhas
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2">
          {isCustomEdited && (
            <button
              type="button"
              onClick={handleRestore}
              className="inline-flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors border border-slate-200"
              title="Restaurar texto gerado automaticamente pelas variáveis"
            >
              <RotateCcw className="w-3.5 h-3.5 text-slate-500" />
              <span>Restaurar original</span>
            </button>
          )}

          <button
            type="button"
            onClick={handleCopy}
            className={`inline-flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-bold rounded-lg transition-all shadow-xs ${
              copied
                ? 'bg-emerald-600 text-white shadow-emerald-600/20'
                : 'bg-blue-600 hover:bg-blue-700 text-white shadow-blue-200'
            }`}
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-white" />
                <span>Copiado!</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span>Copiar Mensagem</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Editor & Content */}
      <div className="space-y-3">
        {isCustomEdited && (
          <div className="p-2.5 bg-amber-50 border border-amber-200 rounded-lg flex items-center justify-between text-xs text-amber-800">
            <span className="flex items-center gap-1.5">
              <AlertCircle className="w-3.5 h-3.5 text-amber-600" />
              Você fez edições manuais no texto. O recálculo automático preservará suas alterações.
            </span>
            <button
              type="button"
              onClick={handleRestore}
              className="underline font-semibold hover:text-amber-950 ml-2"
            >
              Restaurar
            </button>
          </div>
        )}

        <div className="relative">
          <textarea
            rows={14}
            value={emailText}
            onChange={handleTextChange}
            className="w-full font-mono text-xs leading-relaxed p-4 rounded-lg border border-slate-200 bg-slate-50/70 text-slate-800 focus:bg-white focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20 focus:outline-hidden resize-y transition-all shadow-2xs"
            placeholder="O modelo de email será gerado aqui..."
          />
        </div>

        <div className="flex items-center justify-between text-[11px] text-slate-400 pt-1">
          <span>
            {emailText.length} caracteres • Pronto para envio via Gmail / Outlook
          </span>
          <span className="hidden sm:inline font-medium text-slate-400">
            Edições manuais são salvas localmente
          </span>
        </div>
      </div>
    </section>
  );
};

