import React, { useState, useEffect, useMemo } from 'react';
import { Campaign, UsageData } from './types';
import {
  DEFAULT_USAGE,
  DEFAULT_RATE,
  DEFAULT_BALANCE,
  DEFAULT_CAMPAIGNS,
} from './constants/pricing';
import {
  getIndicatorRows,
  calculateFinancialSummary,
  generateEmailTemplate,
} from './utils/calculations';
import { Header } from './components/Header';
import { KeyMetrics } from './components/KeyMetrics';
import { UsageSection } from './components/UsageSection';
import { ProjectionSection } from './components/ProjectionSection';
import { CampaignsSection } from './components/CampaignsSection';
import { SummarySection } from './components/SummarySection';
import { EmailSection } from './components/EmailSection';
import { TariffModal } from './components/TariffModal';
import { ResetConfirmModal } from './components/ResetConfirmModal';

const STORAGE_KEY = 'rd_conversas_forecast_v1';

export default function App() {
  // Load initial state from LocalStorage or fall back to spreadsheet defaults
  const [usage, setUsage] = useState<UsageData>(() => {
    try {
      const saved = localStorage.getItem(`${STORAGE_KEY}_usage`);
      return saved ? JSON.parse(saved) : DEFAULT_USAGE;
    } catch {
      return DEFAULT_USAGE;
    }
  });

  const [ratePercent, setRatePercent] = useState<number>(() => {
    try {
      const saved = localStorage.getItem(`${STORAGE_KEY}_rate`);
      return saved !== null ? JSON.parse(saved) : DEFAULT_RATE;
    } catch {
      return DEFAULT_RATE;
    }
  });

  const [campaigns, setCampaigns] = useState<Campaign[]>(() => {
    try {
      const saved = localStorage.getItem(`${STORAGE_KEY}_campaigns`);
      return saved ? JSON.parse(saved) : DEFAULT_CAMPAIGNS;
    } catch {
      return DEFAULT_CAMPAIGNS;
    }
  });

  const [currentBalance, setCurrentBalance] = useState<number>(() => {
    try {
      const saved = localStorage.getItem(`${STORAGE_KEY}_balance`);
      return saved !== null ? JSON.parse(saved) : DEFAULT_BALANCE;
    } catch {
      return DEFAULT_BALANCE;
    }
  });

  // Modal states
  const [isTariffsOpen, setIsTariffsOpen] = useState(false);
  const [isResetConfirmOpen, setIsResetConfirmOpen] = useState(false);

  // Sync to LocalStorage on changes
  useEffect(() => {
    try {
      localStorage.setItem(`${STORAGE_KEY}_usage`, JSON.stringify(usage));
      localStorage.setItem(`${STORAGE_KEY}_rate`, JSON.stringify(ratePercent));
      localStorage.setItem(`${STORAGE_KEY}_campaigns`, JSON.stringify(campaigns));
      localStorage.setItem(`${STORAGE_KEY}_balance`, JSON.stringify(currentBalance));
    } catch (e) {
      console.error('Falha ao salvar dados no LocalStorage:', e);
    }
  }, [usage, ratePercent, campaigns, currentBalance]);

  // Calculations
  const indicatorRows = useMemo(
    () => getIndicatorRows(usage, ratePercent),
    [usage, ratePercent]
  );

  const summary = useMemo(
    () => calculateFinancialSummary(usage, ratePercent, campaigns, currentBalance),
    [usage, ratePercent, campaigns, currentBalance]
  );

  const autoGeneratedEmail = useMemo(
    () => generateEmailTemplate(summary, campaigns),
    [summary, campaigns]
  );

  // Handlers
  const handleUsageChange = (key: keyof UsageData, value: number) => {
    setUsage((prev) => ({ ...prev, [key]: value }));
  };

  const handleRateChange = (value: number) => {
    setRatePercent(value);
  };

  const handleAddCampaign = (campaign: Campaign) => {
    setCampaigns((prev) => [...prev, campaign]);
  };

  const handleUpdateCampaign = (updated: Campaign) => {
    setCampaigns((prev) =>
      prev.map((c) => (c.id === updated.id ? updated : c))
    );
  };

  const handleDeleteCampaign = (id: string) => {
    setCampaigns((prev) => prev.filter((c) => c.id !== id));
  };

  const handleDuplicateCampaign = (campaign: Campaign) => {
    const duplicated: Campaign = {
      ...campaign,
      id: `camp-${Date.now()}`,
      name: `${campaign.name} (Cópia)`,
    };
    setCampaigns((prev) => [...prev, duplicated]);
  };

  const handleBalanceChange = (value: number) => {
    setCurrentBalance(value);
  };

  const handleResetDefaults = () => {
    setUsage(DEFAULT_USAGE);
    setRatePercent(DEFAULT_RATE);
    setCampaigns(DEFAULT_CAMPAIGNS);
    setCurrentBalance(DEFAULT_BALANCE);
    try {
      localStorage.removeItem(`${STORAGE_KEY}_usage`);
      localStorage.removeItem(`${STORAGE_KEY}_rate`);
      localStorage.removeItem(`${STORAGE_KEY}_campaigns`);
      localStorage.removeItem(`${STORAGE_KEY}_balance`);
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col selection:bg-sky-100 selection:text-sky-900">
      {/* Top Navbar */}
      <Header
        onOpenTariffs={() => setIsTariffsOpen(true)}
        onOpenReset={() => setIsResetConfirmOpen(true)}
      />

      {/* Main Content */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-6">
        {/* Page Hero Header */}
        <div className="bg-white rounded-xl p-5 sm:p-6 border border-slate-200 shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-blue-50 text-blue-700 text-[11px] font-bold border border-blue-100 mb-1.5">
              <span className="h-1.5 w-1.5 rounded-full bg-blue-600"></span>
              Calculadora Financeira & Operacional
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight">
              Previsão de Uso — RD Conversas
            </h2>
            <p className="text-xs text-slate-500 mt-1 max-w-2xl font-medium">
              Controle de consumo, projeção de crescimento, dimensionamento de campanhas e cálculo automático de recarga pré-paga.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <div className="p-3 bg-slate-50 rounded-lg border border-slate-200 text-right">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
                Janela Padrão
              </span>
              <span className="text-xs font-bold text-slate-900 font-mono">
                15 Dias
              </span>
            </div>
          </div>
        </div>

        {/* Top 4 Summary Cards */}
        <KeyMetrics
          summary={summary}
          ratePercent={ratePercent}
          campaignsCount={campaigns.length}
        />

        {/* Section 1: Usage in last 15 days */}
        <UsageSection
          usage={usage}
          indicatorRows={indicatorRows}
          totalCost={summary.currentUsageCost}
          onUsageChange={handleUsageChange}
          onOpenTariffs={() => setIsTariffsOpen(true)}
        />

        {/* Section 2: Rate Simulator & 15-Day Projection Table */}
        <ProjectionSection
          ratePercent={ratePercent}
          indicatorRows={indicatorRows}
          projectedTotalCost={summary.projectedUsageCost}
          onRateChange={handleRateChange}
        />

        {/* Section 3: Campaigns List & Management */}
        <CampaignsSection
          campaigns={campaigns}
          totalCampaignsCost={summary.campaignsTotalCost}
          onAddCampaign={handleAddCampaign}
          onUpdateCampaign={handleUpdateCampaign}
          onDeleteCampaign={handleDeleteCampaign}
          onDuplicateCampaign={handleDuplicateCampaign}
        />

        {/* Section 4: Current Balance & Summary Math */}
        <SummarySection
          summary={summary}
          currentBalance={currentBalance}
          onBalanceChange={handleBalanceChange}
        />

        {/* Section 5: Recharge Request Email for Directors */}
        <EmailSection autoGeneratedEmail={autoGeneratedEmail} />
      </main>

      {/* Footer */}
      <footer className="no-print mt-12 border-t border-slate-200 bg-white py-6">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500">
          <div>
            <span className="font-semibold text-slate-700">RD Conversas</span> — Controle de utilização e previsão de recarga.
          </div>
          <div className="flex items-center gap-4">
            <button
              type="button"
              onClick={() => setIsTariffsOpen(true)}
              className="hover:text-sky-600 transition-colors"
            >
              Tabela de Tarifas
            </button>
            <button
              type="button"
              onClick={() => setIsResetConfirmOpen(true)}
              className="hover:text-rose-600 transition-colors"
            >
              Restaurar Padrões
            </button>
          </div>
        </div>
      </footer>

      {/* Modals */}
      <TariffModal
        isOpen={isTariffsOpen}
        onClose={() => setIsTariffsOpen(false)}
      />

      <ResetConfirmModal
        isOpen={isResetConfirmOpen}
        onClose={() => setIsResetConfirmOpen(false)}
        onConfirm={handleResetDefaults}
      />
    </div>
  );
}
